-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js. Flavor: purr
local M = {}

-- palette
local palette = {}
palette.bg = "#2B2833"
palette.bg_mantle = "#24212B"
palette.bg_crust = "#201E27"
palette.surface0 = "#4A4557"
palette.surface1 = "#5C586A"
palette.surface2 = "#6E687D"

palette.fg = "#ECE7EE"
palette.fg_sub0 = "#D9D4DE"
palette.fg_sub1 = "#B7B0C0"
palette.fg_overlay = "#7A7485"

palette.acc_peach = "#F2B8B2"
palette.acc_mint = "#8FCFA0"
palette.acc_cream = "#F8EAA3"
palette.acc_peri = "#B4C5ED"
palette.acc_pink = "#F5C2E7"
palette.acc_lilac = "#BFA8F6"
palette.acc_aqua = "#8EE8E4"
palette.acc_ember = "#F26D6D"
palette.acc_honey = "#E6B85A"
palette.acc_skybell = "#6EA6F6"
palette.acc_leaflight = "#A9DDBB"
palette.acc_ash = "#3B3740"
palette.acc_glimmer = "#CDE8F2"

local util = require("meowllow.util")

local c = palette

local highlights = {
  Normal       = { fg = c.fg, bg = c.bg },
  NormalFloat  = { fg = c.fg, bg = c.bg_mantle },
  FloatBorder  = { fg = c.acc_peri, bg = c.bg_mantle },
  CursorLine   = { bg = c.surface0 },
  CursorLineNr = { fg = c.acc_peri },
  LineNr       = { fg = c.fg_sub1 },
  Visual       = { bg = c.acc_peri },
  Comment      = { fg = c.fg_overlay, italic = true },
  String       = { fg = c.acc_peach },
  Number       = { fg = c.acc_pink },
  Keyword      = { fg = c.acc_peri, italic = true },
  Function     = { fg = c.acc_lilac, italic = true },
  Type         = { fg = c.acc_mint },
  Constant     = { fg = c.acc_cream },
  Identifier   = { fg = c.fg },
  Operator     = { fg = c.fg_sub1 },
  ["@comment"]     = { fg = c.fg_overlay, italic = true },
  ["@keyword"]     = { fg = c.acc_peri, italic = true },
  ["@string"]      = { fg = c.acc_peach },
  ["@number"]      = { fg = c.acc_pink },
  ["@type"]        = { fg = c.acc_mint },
  ["@function"]    = { fg = c.acc_lilac },
  ["@property"]    = { fg = c.acc_aqua },
  ["@variable"]    = { fg = c.fg },
  ["@constant"]    = { fg = c.acc_cream },
  DiagnosticError = { fg = c.acc_ember },
  DiagnosticWarn  = { fg = c.acc_honey },
  DiagnosticInfo  = { fg = c.acc_skybell },
  DiagnosticHint  = { fg = c.acc_leaflight },

  DiagnosticUnderlineError = { undercurl = true, sp = c.acc_ember },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = c.acc_honey },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = c.acc_skybell },
  DiagnosticUnderlineHint  = { undercurl = true, sp = c.acc_leaflight },
  GitSignsAdd    = { fg = c.acc_leaflight },
  GitSignsChange = { fg = c.acc_skybell },
  GitSignsDelete = { fg = c.acc_ember },
  TelescopeNormal       = { bg = c.bg_mantle, fg = c.fg },
  TelescopeSelection    = { bg = c.surface0 },
  TelescopePromptNormal = { bg = c.bg_mantle },
}

function M.apply()
  -- ensure groups are applied using util.set_highlights
  util.set_highlights(highlights)
end

return M