-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js. Flavor: slumber
local M = {}

-- palette
local palette = {}
palette.bg = "#2A272E"
palette.bg_mantle = "#242128"
palette.bg_crust = "#1F1D25"
palette.surface0 = "#4A4553"
palette.surface1 = "#575268"
palette.surface2 = "#6E6A86"

palette.fg = "#F6EDE6"
palette.fg_sub0 = "#D8D0C8"
palette.fg_sub1 = "#AFA9B8"
palette.fg_overlay = "#6E6A86"

palette.acc_peach = "#EE99A0"
palette.acc_mint = "#8FCF98"
palette.acc_cream = "#F9E2AF"
palette.acc_peri = "#9FBCE8"
palette.acc_pink = "#F5BDE6"
palette.acc_lilac = "#C7B0F0"
palette.acc_aqua = "#99E1C9"
palette.acc_ember = "#E46A6A"
palette.acc_honey = "#E5B76E"
palette.acc_skybell = "#7FA6F7"
palette.acc_leaflight = "#A6D1A1"
palette.acc_ash = "#3B3640"
palette.acc_glimmer = "#CFEFF0"

local util = require("meowllow.util")

local c = palette

local highlights = {
  Normal       = { fg = c.fg, bg = c.bg },
  NormalFloat  = { fg = c.fg, bg = c.bg_mantle },
  FloatBorder  = { fg = c.acc_peri, bg = c.bg_mantle },
  CursorLine   = { bg = c.surface0 },
  CursorLineNr = { fg = c.acc_peri },
  LineNr       = { fg = c.fg_sub1 },
  Visual       = { bg = c.acc_peri },
  Comment      = { fg = c.fg_overlay, italic = true },
  String       = { fg = c.acc_peach },
  Number       = { fg = c.acc_pink },
  Keyword      = { fg = c.acc_peri, italic = true },
  Function     = { fg = c.acc_lilac, italic = true },
  Type         = { fg = c.acc_mint },
  Constant     = { fg = c.acc_cream },
  Identifier   = { fg = c.fg },
  Operator     = { fg = c.fg_sub1 },
  ["@comment"]     = { fg = c.fg_overlay, italic = true },
  ["@keyword"]     = { fg = c.acc_peri, italic = true },
  ["@string"]      = { fg = c.acc_peach },
  ["@number"]      = { fg = c.acc_pink },
  ["@type"]        = { fg = c.acc_mint },
  ["@function"]    = { fg = c.acc_lilac },
  ["@property"]    = { fg = c.acc_aqua },
  ["@variable"]    = { fg = c.fg },
  ["@constant"]    = { fg = c.acc_cream },
  DiagnosticError = { fg = c.acc_ember },
  DiagnosticWarn  = { fg = c.acc_honey },
  DiagnosticInfo  = { fg = c.acc_skybell },
  DiagnosticHint  = { fg = c.acc_leaflight },

  DiagnosticUnderlineError = { undercurl = true, sp = c.acc_ember },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = c.acc_honey },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = c.acc_skybell },
  DiagnosticUnderlineHint  = { undercurl = true, sp = c.acc_leaflight },
  GitSignsAdd    = { fg = c.acc_leaflight },
  GitSignsChange = { fg = c.acc_skybell },
  GitSignsDelete = { fg = c.acc_ember },
  TelescopeNormal       = { bg = c.bg_mantle, fg = c.fg },
  TelescopeSelection    = { bg = c.surface0 },
  TelescopePromptNormal = { bg = c.bg_mantle },
}

function M.apply()
  -- ensure groups are applied using util.set_highlights
  util.set_highlights(highlights)
end

return M