-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js. Flavor: sunbeam
local M = {}

-- palette
local palette = {}
palette.bg = "#FDFBF8"
palette.bg_mantle = "#F9F6F2"
palette.bg_crust = "#F8F4F0"
palette.surface0 = "#F2ECE4"
palette.surface1 = "#E8E1DA"
palette.surface2 = "#DFD8CF"

palette.fg = "#423F3A"
palette.fg_sub0 = "#6D6863"
palette.fg_sub1 = "#8E8982"
palette.fg_overlay = "#B0A9A3"

palette.acc_peach = "#E88E86"
palette.acc_mint = "#5FA872"
palette.acc_cream = "#E6B450"
palette.acc_peri = "#7E9CD6"
palette.acc_pink = "#E59BCF"
palette.acc_lilac = "#AB91E4"
palette.acc_aqua = "#5EC2B8"
palette.acc_ember = "#C94B4B"
palette.acc_honey = "#C98939"
palette.acc_skybell = "#5279C6"
palette.acc_leaflight = "#81B580"
palette.acc_ash = "#DDD7D1"
palette.acc_glimmer = "#FFF3E1"

local util = require("meowllow.util")

local c = palette

local highlights = {
  Normal       = { fg = c.fg, bg = c.bg },
  NormalFloat  = { fg = c.fg, bg = c.bg_mantle },
  FloatBorder  = { fg = c.acc_peri, bg = c.bg_mantle },
  CursorLine   = { bg = c.surface0 },
  CursorLineNr = { fg = c.acc_peri },
  LineNr       = { fg = c.fg_sub1 },
  Visual       = { bg = c.acc_peri },
  Comment      = { fg = c.fg_overlay, italic = true },
  String       = { fg = c.acc_peach },
  Number       = { fg = c.acc_pink },
  Keyword      = { fg = c.acc_peri, italic = true },
  Function     = { fg = c.acc_lilac, italic = true },
  Type         = { fg = c.acc_mint },
  Constant     = { fg = c.acc_cream },
  Identifier   = { fg = c.fg },
  Operator     = { fg = c.fg_sub1 },
  ["@comment"]     = { fg = c.fg_overlay, italic = true },
  ["@keyword"]     = { fg = c.acc_peri, italic = true },
  ["@string"]      = { fg = c.acc_peach },
  ["@number"]      = { fg = c.acc_pink },
  ["@type"]        = { fg = c.acc_mint },
  ["@function"]    = { fg = c.acc_lilac },
  ["@property"]    = { fg = c.acc_aqua },
  ["@variable"]    = { fg = c.fg },
  ["@constant"]    = { fg = c.acc_cream },
  DiagnosticError = { fg = c.acc_ember },
  DiagnosticWarn  = { fg = c.acc_honey },
  DiagnosticInfo  = { fg = c.acc_skybell },
  DiagnosticHint  = { fg = c.acc_leaflight },

  DiagnosticUnderlineError = { undercurl = true, sp = c.acc_ember },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = c.acc_honey },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = c.acc_skybell },
  DiagnosticUnderlineHint  = { undercurl = true, sp = c.acc_leaflight },
  GitSignsAdd    = { fg = c.acc_leaflight },
  GitSignsChange = { fg = c.acc_skybell },
  GitSignsDelete = { fg = c.acc_ember },
  TelescopeNormal       = { bg = c.bg_mantle, fg = c.fg },
  TelescopeSelection    = { bg = c.surface0 },
  TelescopePromptNormal = { bg = c.bg_mantle },
}

function M.apply()
  -- ensure groups are applied using util.set_highlights
  util.set_highlights(highlights)
end

return M