import fs from "fs-extra";
import path from "path";

export async function generateNvim(palette) {
    const base = path.join("nvim");
    const colorsDir = path.join(base, "colors");
    const luaDir = path.join(base, "lua", "meowllow");
    const themesDir = path.join(luaDir, "themes");

    await fs.ensureDir(colorsDir);
    await fs.ensureDir(luaDir);
    await fs.ensureDir(themesDir);

    // palette.lua - produces a Lua table mirroring your YAML palette
    const paletteLua = buildPaletteModule(palette);
    await fs.writeFile(path.join(luaDir, "palette.lua"), paletteLua, "utf8");

    // themes/<flavor>.lua
    for (const [flavor, colors] of Object.entries(palette)) {
        const themeLua = buildThemeModule(flavor, colors);
        await fs.writeFile(path.join(themesDir, `${flavor}.lua`), themeLua, "utf8");

        // colors/meowllow-<flavor>.lua loader
        const colorsLoader = `-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js\nrequire("meowllow.themes.${flavor}").apply()\n`;
        await fs.writeFile(path.join(colorsDir, `meowllow-${flavor}.lua`), colorsLoader, "utf8");

        console.log(`✓ Generated nvim theme: ${flavor}`);
    }

    console.log(`✓ Generated nvim plugin in ${base}/`);
}

/* ---------- helpers to build Lua modules ---------- */

function dumpTable(obj, indent = 0) {
    // simple Lua table dumper for the palette module
    const pad = "  ".repeat(indent);
    if (typeof obj === "string") {
        return `"${obj}"`;
    } else if (typeof obj === "object" && obj !== null && !Array.isArray(obj)) {
        const parts = ["{"];
        for (const [k, v] of Object.entries(obj)) {
            parts.push(`${pad}  ${k} = ${dumpTable(v, indent + 1)},`);
        }
        parts.push(`${pad}}`);
        return parts.join("\n");
    } else if (Array.isArray(obj)) {
        const parts = ["{"];
        for (const v of obj) parts.push(`${pad}  ${dumpTable(v, indent + 1)},`);
        parts.push(`${pad}}`);
        return parts.join("\n");
    } else {
        return "nil";
    }
}

function buildPaletteModule(palette) {
    // palette: JS object from YAML. Convert to Lua table representation.
    const lines = [];
    lines.push("-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js");
    lines.push("local M = {}");
    lines.push("");

    for (const [flavor, data] of Object.entries(palette)) {
        lines.push(`M.${flavor} = ${dumpTable(data, 0)}`);
        lines.push("");
    }

    lines.push("return M");
    return lines.join("\n");
}

function buildThemeModule(flavor, c) {
    const bg = c.bg || {};
    const text = c.text || {};
    const acc = c.accents || {};

    // create the colors table (string literal)
    const colorsTable = [
        "local palette = {}",
        `palette.bg = "${bg.base || ""}"`,
        `palette.bg_mantle = "${bg.mantle || ""}"`,
        `palette.bg_crust = "${bg.crust || ""}"`,
        `palette.surface0 = "${bg.surface0 || ""}"`,
        `palette.surface1 = "${bg.surface1 || ""}"`,
        `palette.surface2 = "${bg.surface2 || ""}"`,
        ``,
        `palette.fg = "${text.main || ""}"`,
        `palette.fg_sub0 = "${text.sub0 || ""}"`,
        `palette.fg_sub1 = "${text.sub1 || ""}"`,
        `palette.fg_overlay = "${text.overlay0 || ""}"`,
        ``,
    ];

    // accents
    for (const [k, v] of Object.entries(acc)) {
        colorsTable.push(`palette.acc_${k} = "${v}"`);
    }

    // build the module content
    const lines = [];
    lines.push(`-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js. Flavor: ${flavor}`);
    lines.push(`local M = {}`);
    lines.push("");
    lines.push("-- palette");
    lines.push(...colorsTable);
    lines.push("");
    lines.push('local util = require("meowllow.util")');
    lines.push("");
    lines.push("local c = palette");
    lines.push("");
    lines.push("local highlights = {");

    // core UI
    lines.push(`  Normal       = { fg = c.fg, bg = c.bg },`);
    lines.push(`  NormalFloat  = { fg = c.fg, bg = c.bg_mantle },`);
    lines.push(`  FloatBorder  = { fg = c.acc_peri, bg = c.bg_mantle },`);
    lines.push(`  CursorLine   = { bg = c.surface0 },`);
    lines.push(`  CursorLineNr = { fg = c.acc_peri },`);
    lines.push(`  LineNr       = { fg = c.fg_sub1 },`);
    lines.push(`  Visual       = { bg = c.acc_peri },`);

    // syntax
    lines.push(`  Comment      = { fg = c.fg_overlay, italic = true },`);
    lines.push(`  String       = { fg = c.acc_peach },`);
    lines.push(`  Number       = { fg = c.acc_pink },`);
    lines.push(`  Keyword      = { fg = c.acc_peri, italic = true },`);
    lines.push(`  Function     = { fg = c.acc_lilac, italic = true },`);
    lines.push(`  Type         = { fg = c.acc_mint },`);
    lines.push(`  Constant     = { fg = c.acc_cream },`);
    lines.push(`  Identifier   = { fg = c.fg },`);
    lines.push(`  Operator     = { fg = c.fg_sub1 },`);

    // treesitter-ish groups (names that nvim-treesitter uses)
    lines.push(`  ["@comment"]     = { fg = c.fg_overlay, italic = true },`);
    lines.push(`  ["@keyword"]     = { fg = c.acc_peri, italic = true },`);
    lines.push(`  ["@string"]      = { fg = c.acc_peach },`);
    lines.push(`  ["@number"]      = { fg = c.acc_pink },`);
    lines.push(`  ["@type"]        = { fg = c.acc_mint },`);
    lines.push(`  ["@function"]    = { fg = c.acc_lilac },`);
    lines.push(`  ["@property"]    = { fg = c.acc_aqua },`);
    lines.push(`  ["@variable"]    = { fg = c.fg },`);
    lines.push(`  ["@constant"]    = { fg = c.acc_cream },`);

    // diagnostics
    lines.push(`  DiagnosticError = { fg = c.acc_ember },`);
    lines.push(`  DiagnosticWarn  = { fg = c.acc_honey },`);
    lines.push(`  DiagnosticInfo  = { fg = c.acc_skybell },`);
    lines.push(`  DiagnosticHint  = { fg = c.acc_leaflight },`);
    lines.push("");
    // underlines
    lines.push(`  DiagnosticUnderlineError = { undercurl = true, sp = c.acc_ember },`);
    lines.push(`  DiagnosticUnderlineWarn  = { undercurl = true, sp = c.acc_honey },`);
    lines.push(`  DiagnosticUnderlineInfo  = { undercurl = true, sp = c.acc_skybell },`);
    lines.push(`  DiagnosticUnderlineHint  = { undercurl = true, sp = c.acc_leaflight },`);

    // git signs
    lines.push(`  GitSignsAdd    = { fg = c.acc_leaflight },`);
    lines.push(`  GitSignsChange = { fg = c.acc_skybell },`);
    lines.push(`  GitSignsDelete = { fg = c.acc_ember },`);

    // telescope
    lines.push(`  TelescopeNormal       = { bg = c.bg_mantle, fg = c.fg },`);
    lines.push(`  TelescopeSelection    = { bg = c.surface0 },`);
    lines.push(`  TelescopePromptNormal = { bg = c.bg_mantle },`);

    lines.push("}");
    lines.push("");
    lines.push("function M.apply()");
    lines.push("  -- ensure groups are applied using util.set_highlights");
    lines.push("  util.set_highlights(highlights)");
    lines.push("end");
    lines.push("");
    lines.push("return M");

    return lines.join("\n");
}
