-- Auto-generated by Meowllow build system for nvim at src/generators/nvim.js
local M = {}

M.purr = {
  bg = {
    crust = "#201E27",
    mantle = "#24212B",
    base = "#2B2833",
    surface0 = "#4A4557",
    surface1 = "#5C586A",
    surface2 = "#6E687D",
  },
  text = {
    main = "#ECE7EE",
    sub0 = "#D9D4DE",
    sub1 = "#B7B0C0",
    overlay0 = "#7A7485",
  },
  accents = {
    peach = "#F2B8B2",
    mint = "#8FCFA0",
    cream = "#F8EAA3",
    peri = "#B4C5ED",
    pink = "#F5C2E7",
    lilac = "#BFA8F6",
    aqua = "#8EE8E4",
    ember = "#F26D6D",
    honey = "#E6B85A",
    skybell = "#6EA6F6",
    leaflight = "#A9DDBB",
    ash = "#3B3740",
    glimmer = "#CDE8F2",
  },
}

M.slumber = {
  bg = {
    crust = "#1F1D25",
    mantle = "#242128",
    base = "#2A272E",
    surface0 = "#4A4553",
    surface1 = "#575268",
    surface2 = "#6E6A86",
  },
  text = {
    main = "#F6EDE6",
    sub0 = "#D8D0C8",
    sub1 = "#AFA9B8",
    overlay0 = "#6E6A86",
  },
  accents = {
    peach = "#EE99A0",
    mint = "#8FCF98",
    cream = "#F9E2AF",
    peri = "#9FBCE8",
    pink = "#F5BDE6",
    lilac = "#C7B0F0",
    aqua = "#99E1C9",
    ember = "#E46A6A",
    honey = "#E5B76E",
    skybell = "#7FA6F7",
    leaflight = "#A6D1A1",
    ash = "#3B3640",
    glimmer = "#CFEFF0",
  },
}

M.sunbeam = {
  bg = {
    crust = "#F8F4F0",
    mantle = "#F9F6F2",
    base = "#FDFBF8",
    surface0 = "#F2ECE4",
    surface1 = "#E8E1DA",
    surface2 = "#DFD8CF",
  },
  text = {
    main = "#423F3A",
    sub0 = "#6D6863",
    sub1 = "#8E8982",
    overlay0 = "#B0A9A3",
  },
  accents = {
    peach = "#E88E86",
    mint = "#5FA872",
    cream = "#E6B450",
    peri = "#7E9CD6",
    pink = "#E59BCF",
    lilac = "#AB91E4",
    aqua = "#5EC2B8",
    ember = "#C94B4B",
    honey = "#C98939",
    skybell = "#5279C6",
    leaflight = "#81B580",
    ash = "#DDD7D1",
    glimmer = "#FFF3E1",
  },
}

return M